site_name: Personal Ledger
site_url: https://ianteda.github.io/personal_ledger
repo_url: https://github.com/IanTeda/personal_ledger 
docs_dir: 'docs'
theme:
  name: 'material'
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.path
    - navigation.top
nav:
  - Home: README.md
  - About: about.md
  - References: references.md
plugins:
  - search
  - optimize
  - neoteroi.mkdocsoad:
      use_pymdownx: true
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/neoteroi-mkdocsoad.css
extra_javascript:
  - javascript/plausible.js
