site_name: Personal Ledger
site_url: https://ianteda.github.io/personal_ledger
repo_url: https://github.com/IanTeda/personal_ledger 
docs_dir: 'docs'
theme:
  name: 'material'
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
nav:
  - Home: README.md
  - Getting Started: getting_started.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - References: references.md
  - Similar Projects: similar_projects.md
plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/neoteroi-mkdocsoad.css
extra_javascript:
  - javascripts/plausible.js
