name: Build Repositotry Documents (MkDocs)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check latest version of actions https://github.com/actions
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Build MkDocs
        # Need to install `mkdocs` and theme `mkdocs-windmill` set in `./mkdocs.yaml` config
        run: pip install mkdocs mkdocs-material neoteroi-mkdocs pymdown-extensions
      - name: Push to Github Pages branch
        # Repository > Settings > Pages > Build and deployment > Branch > gh-pages
        # Repository > Settings > Actions > General > Workflow permissions > Read and write permissions
        run: mkdocs gh-deploy --force --clean --verbose

## References
# https://github.com/Neoteroi/mkdocs-plugins
# https://github.com/actions
# https://squidfunk.github.io/mkdocs-material/publishing-your-site/
